apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-app-dev-dev-canary
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: protected
  rules:
  - host: spring-canary.corp.olacabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-app-dev-dev-canary
            port:
              number: 8080